"use client";

import React, { useState } from "react";
import { X, Copy, Check, Share2, FileText } from "lucide-react";

interface HisaabExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  month: string; // YYYY-MM
  summary: {
    totalExpense: number;
    totalIncome: number;
    netSavings: number;
    totalWaterJars: number;
    totalElectricityUnits: number;
    totalMilkPackets: number;
    waterJarPrice?: number;
    milkPacketPrice?: number;
    rentAmount?: number;
    wifiAmount?: number;
    unsettledSplitTotal?: number;
    categoryBreakdown?: Record<string, number>;
  };
}

export function HisaabExportModal({
  isOpen,
  onClose,
  month,
  summary,
}: HisaabExportModalProps) {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const waterCost = (summary.totalWaterJars || 0) * (summary.waterJarPrice || 50);
  const milkCost = (summary.totalMilkPackets || 0) * (summary.milkPacketPrice || 55);

  const textReport = `🇳🇵 Monthly Hisaab-Kitaab (${month})
━━━━━━━━━━━━━━━━━━━━━━━━━
💰 Total Expenses: Rs. ${summary.totalExpense.toLocaleString()}
💵 Total Income: Rs. ${summary.totalIncome.toLocaleString()}
✨ Net Savings: Rs. ${summary.netSavings.toLocaleString()}

🏠 Household & Utilities:
• 💧 Water Jars: ${summary.totalWaterJars || 0} jars (~Rs. ${waterCost})
• ⚡ Electricity: ${summary.totalElectricityUnits || 0} units
• 🥛 Milk Packets: ${summary.totalMilkPackets || 0} packets (~Rs. ${milkCost})
${summary.rentAmount ? `• 🏠 Room Rent: Rs. ${summary.rentAmount.toLocaleString()}\n` : ""}${summary.wifiAmount ? `• 🌐 WiFi Bill: Rs. ${summary.wifiAmount.toLocaleString()}\n` : ""}
${
  summary.unsettledSplitTotal && summary.unsettledSplitTotal > 0
    ? `👥 Roommate Split Due: Rs. ${summary.unsettledSplitTotal.toLocaleString()}\n`
    : ""
}━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by HabitTrack 🚀`;

  const handleCopy = () => {
    navigator.clipboard.writeText(textReport);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-xs">
      <div className="relative w-full max-w-md bg-white dark:bg-gray-900 rounded-3xl border border-gray-100 dark:border-gray-800 shadow-2xl p-6 sm:p-8 my-8">
        <div className="flex items-center justify-between pb-4 border-b border-gray-100 dark:border-gray-800">
          <div className="flex items-center gap-2">
            <span className="p-2 rounded-xl bg-forest-50 dark:bg-forest-950/40 text-forest-700 dark:text-forest-400">
              <FileText className="w-5 h-5" />
            </span>
            <div>
              <h3 className="text-lg font-black text-gray-900 dark:text-gray-100 tracking-tight">
                Monthly Hisaab Export
              </h3>
              <p className="text-xs text-gray-500 dark:text-gray-400">
                Formatted for WhatsApp or record keeping
              </p>
            </div>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="p-2 rounded-xl text-gray-400 hover:text-gray-600 dark:hover:text-gray-200 hover:bg-gray-100 dark:hover:bg-gray-800"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        <div className="mt-5">
          <pre className="p-4 bg-gray-50 dark:bg-gray-800/60 rounded-2xl border border-gray-200 dark:border-gray-700 text-xs font-mono text-gray-800 dark:text-gray-200 whitespace-pre-wrap select-all leading-relaxed max-h-72 overflow-y-auto">
            {textReport}
          </pre>
        </div>

        <div className="flex items-center justify-between gap-3 mt-6 pt-4 border-t border-gray-100 dark:border-gray-800">
          <button
            type="button"
            onClick={onClose}
            className="px-4 py-2 text-xs font-bold text-gray-500 hover:text-gray-900 dark:hover:text-gray-100"
          >
            Close
          </button>

          <button
            type="button"
            onClick={handleCopy}
            className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-forest-700 hover:bg-forest-800 text-white text-xs font-extrabold shadow-sm transition-all"
          >
            {copied ? (
              <>
                <Check className="w-4 h-4 text-emerald-300" />
                Copied to Clipboard!
              </>
            ) : (
              <>
                <Copy className="w-4 h-4" />
                Copy for WhatsApp
              </>
            )}
          </button>
        </div>
      </div>
    </div>
  );
}
